language: cpp
dist: trusty
os: linux
cache: apt
branches:
  only:
    - travis_continue

env: BUILD_TYPE=RelWithDebInfo

jobs:
  include:
   - env: VERIFY_FLAGS="--vac"
   - env: VERIFY_FLAGS="--cex"
   - env: VERIFY_FLAGS="--cex --horn-bmc-solver=smt-y2"
   - env: VERIFY_FLAGS="--vac --horn-bmc-solver=smt-y2"
   - env: VERIFY_FLAGS=""
  allow_failures:
   - env: VERIFY_FLAGS="--cex"
   - env: VERIFY_FLAGS="--cex --horn-bmc-solver=smt-y2"
  

script: 
- docker build -t verify-c-common -f docker/verify-c-common.Dockerfile .
- |
  travis_wait 120 sleep infinity &
  docker run -t verify-c-common /bin/bash -c "cd build && env VERIFY_FLAGS=$VERIFY_FLAGS ninja test"

services:
  - docker

install: true

