language: cpp
dist: trusty
os: linux
cache: apt
branches:
  only:
    - master
matrix:
  include:
   - env: BUILD_TYPE=RelWithDebInfo
     script:
<<<<<<< HEAD
      - docker build -t verify-c-common -f docker/verify-c-common.Dockerfile .
      - |
        travis_wait 120 sleep infinity &
        docker run -t verify-c-common /bin/bash -c "cd build && ninja test"
      - |
        travis_wait 120 sleep infinity &
        docker run -t verify-c-common /bin/bash -c 'cd build && env VERIFY_FLAGS="--vac" ninja test'
=======
      - docker build -t verify-c-common -f verify-c-common.Dockerfile .
      - docker run --rm -it verify-c-common
      - cd build
      - cmake --build . --target test
>>>>>>> Add tests
services:
  - docker

install: true

