name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        verify_flag: ["", "--vac", "--vac --horn-bmc-solver=smt-y2", "--cex", "--cex --horn-bmc-solver=smt-y2"]
       
    steps:
      - name: Checkout 
        uses: actions/checkout@master

      - name: Get type
        id: type
        if: endsWith( ${{ matrix.verify_flag }} | tr '\\"' ' ', 'y2 ')
        run: echo ::set-output name=type::$(echo ${{ matrix.verify_flag }} | cut -c4-6)
       
      - name: Get exclude test
        id: exclude_files
        run: echo ::set-output name=exclude_files::$(cat ".github/workflows/blacklist.${{steps.type.outputs.type}}.txt" | tr '\n' '|')
     
      - name: Docker 
        run: docker build -t verify-c-common . --file docker/verify-c-common.Dockerfile
        
      - name: Get number of Cores
        id: cores
        run: echo "::set-output name=num_cores::$(nproc --all)"
        
      - name: Run Tests 
        run: docker run -t verify-c-common /bin/bash -c "cd build && env VERIFY_FLAGS=\"${{ matrix.verify_flag }}\" ctest -j ${{steps.cores.outputs.num_cores}} --timeout 2000 -E \"(${{ steps.exclude_files.outputs.exclude_files }})\""
  
